apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Number of replicas you want to run
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: dockerhub_username/my-dockerhub-repo:latest  # Replace with your Docker Hub repository image
        ports:
        - containerPort: 80  # The port your application listens on
        imagePullPolicy: Always  # Always pull the latest image
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80  # The port your application listens on
    targetPort: 80  # The port your container listens on
  type: LoadBalancer  # Expose the service externally using a LoadBalancer (assuming your Kubernetes cluster supports it)
